language: node_js
node_js: "13"
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - stevenbowler@yahoo.com
    - bailee.dast@gmail.com
    - eo30239@gmail.com
    on_success: always # fault: change
    on_failure: always # default: always
cache:
  directories:
    - node_modules
script:
  - echo "hello world"
  - npm run lint
  - npm run testMocha
# before_install:
  # - mysql -e 'CREATE DATABASE testdb;'
 
