language: node_js
node_js: "8"
branches:
  only:
  - master
notifications:
  email:
  - stevenbowler@yahoo.com
  - bailee.dast@gmail.com
  - eo30239@gmail.com
cache:
  directories:
    - node_modules
script:
  - echo "hello world"
  - npm run lint
# before_install:
  # - mysql -e 'CREATE DATABASE testdb;'
 
